services:
  db:
    image: mysql
    container_name: db_oneblog
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_oneblog
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  www:
    build: docker
    container_name: www_oneblog
    ports:
      - "8000:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - dev

#  mailhog:
#    image: mailhog/mailhog
#    container_name: mailhog
#    logging:
#      driver: 'none'
#    ports:
#      - 1025:1025 #SMTP
#      - 8025:8025 #Boite mail
#    networks:
#      - dev

networks:
  dev:

volumes:
  db-data: